/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellNewApplicationRouteImport } from './routes/_shell.new-application'
import { Route as ShellApplicantsIndexRouteImport } from './routes/_shell.applicants.index'
import { Route as ShellApplicantsApplicantIdRouteImport } from './routes/_shell.applicants.$applicantId'
import { Route as ShellResultApplicantIdRouteImport } from './routes/_shell.result.$applicantId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNewApplicationRoute = ShellNewApplicationRouteImport.update({
  id: '/new-application',
  path: '/new-application',
  getParentRoute: () => ShellRoute,
} as any)
const ShellApplicantsIndexRoute = ShellApplicantsIndexRouteImport.update({
  id: '/applicants/',
  path: '/applicants/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellApplicantsApplicantIdRoute =
  ShellApplicantsApplicantIdRouteImport.update({
    id: '/applicants/$applicantId',
    path: '/applicants/$applicantId',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellResultApplicantIdRoute = ShellResultApplicantIdRouteImport.update({
  id: '/result/$applicantId',
  path: '/result/$applicantId',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/new-application': typeof ShellNewApplicationRoute
  '/applicants/$applicantId': typeof ShellApplicantsApplicantIdRoute
  '/result/$applicantId': typeof ShellResultApplicantIdRoute
  '/applicants/': typeof ShellApplicantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/new-application': typeof ShellNewApplicationRoute
  '/applicants/$applicantId': typeof ShellApplicantsApplicantIdRoute
  '/result/$applicantId': typeof ShellResultApplicantIdRoute
  '/applicants': typeof ShellApplicantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/new-application': typeof ShellNewApplicationRoute
  '/_shell/applicants/$applicantId': typeof ShellApplicantsApplicantIdRoute
  '/_shell/result/$applicantId': typeof ShellResultApplicantIdRoute
  '/_shell/applicants/': typeof ShellApplicantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/new-application'
    | '/applicants/$applicantId'
    | '/result/$applicantId'
    | '/applicants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/new-application'
    | '/applicants/$applicantId'
    | '/result/$applicantId'
    | '/applicants'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/analytics'
    | '/_shell/dashboard'
    | '/_shell/new-application'
    | '/_shell/applicants/$applicantId'
    | '/_shell/result/$applicantId'
    | '/_shell/applicants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/new-application': {
      id: '/_shell/new-application'
      path: '/new-application'
      fullPath: '/new-application'
      preLoaderRoute: typeof ShellNewApplicationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/applicants/': {
      id: '/_shell/applicants/'
      path: '/applicants'
      fullPath: '/applicants/'
      preLoaderRoute: typeof ShellApplicantsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/applicants/$applicantId': {
      id: '/_shell/applicants/$applicantId'
      path: '/applicants/$applicantId'
      fullPath: '/applicants/$applicantId'
      preLoaderRoute: typeof ShellApplicantsApplicantIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/result/$applicantId': {
      id: '/_shell/result/$applicantId'
      path: '/result/$applicantId'
      fullPath: '/result/$applicantId'
      preLoaderRoute: typeof ShellResultApplicantIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellNewApplicationRoute: typeof ShellNewApplicationRoute
  ShellApplicantsApplicantIdRoute: typeof ShellApplicantsApplicantIdRoute
  ShellResultApplicantIdRoute: typeof ShellResultApplicantIdRoute
  ShellApplicantsIndexRoute: typeof ShellApplicantsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellNewApplicationRoute: ShellNewApplicationRoute,
  ShellApplicantsApplicantIdRoute: ShellApplicantsApplicantIdRoute,
  ShellResultApplicantIdRoute: ShellResultApplicantIdRoute,
  ShellApplicantsIndexRoute: ShellApplicantsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
